from enum import Enum

class AgentState(str, Enum):
    IDLE = "IDLE"
    RETRIEVING_EXPERIENCE = "RETRIEVING_EXPERIENCE"
    BUILDING_CONTEXT = "BUILDING_CONTEXT"
    GENERATING = "GENERATING"
    EXECUTING = "EXECUTING"
    EVALUATING = "EVALUATING"
    DIAGNOSING = "DIAGNOSING"
    REPAIRING = "REPAIRING"
    RE_EXECUTING = "RE_EXECUTING"
    DISTILLING_EXPERIENCE = "DISTILLING_EXPERIENCE"
    SAVING = "SAVING"
    PASSED = "PASSED"
    FAILED = "FAILED"
    ERROR = "ERROR"
